name: ci

on:
  push:
    branches: [ version_4, version_4.3, main ]
  pull_request:
    branches: [ version_4, version_4.3, main ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v3
    
    - name: compile and run tests
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make -j8 test BASE2_RAISED_BY=16
        make clean
        make -j8 test BASE2_RAISED_BY=32
        make clean
        make -j8 test BASE2_RAISED_BY=64
        make clean